# Generated by Django 6.0.3 on 2026-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='recibir_noticias',
            field=models.BooleanField(default=False, verbose_name='Recibir noticias y novedades'),
        ),
    ]
