# Generated by Django 6.0.3 on 2026-03-17 01:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(validators=[users.models.Persona.validar_fecha_nacimiento]),
        ),
    ]
