# Generated by Django 6.0.3 on 2026-04-23 02:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='lugar_nacimiento',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
