# Generated by Django 6.0.3 on 2026-06-02 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preferencias_recibir_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('titular', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
