# Generated by Django 6.0.3 on 2026-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
