# Generated by Django 6.0.3 on 2026-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tarjeta_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='año_vencimiento',
            field=models.PositiveSmallIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mes_vencimiento',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
