# Generated by Django 6.0.3 on 2026-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tarjeta_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=19, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=19, max_length=20),
            preserve_default=False,
        ),
    ]
