# Generated by Django 6.0.3 on 2026-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cliente_latitud_cliente_longitud'),
        ('users', '0006_cuponcumpleanos'),
    ]

    operations = [
    ]
