# Generated by Django 6.0.3 on 2026-06-09 17:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20260609_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponcumpleanos',
            name='anio_generado',
            field=models.PositiveIntegerField(default=users.models.CuponCumpleanos.anio_actual),
        ),
    ]
