# Generated by Django 6.0.3 on 2026-05-29 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField(default=50)),
                ('numero_paginas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)])),
                ('issn', models.CharField(max_length=50, unique=True)),
                ('año_publicacion', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MaxValueValidator(2026)])),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('autores', models.ManyToManyField(to='libros.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.editorial')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.genero')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.idioma')),
            ],
        ),
    ]
