# Generated by Django 6.0.3 on 2026-04-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_publicacion', models.IntegerField()),
                ('numero_paginas', models.IntegerField()),
                ('editorial', models.CharField(max_length=150)),
                ('issn', models.CharField(max_length=50, unique=True)),
                ('idioma', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.autor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.genero')),
            ],
        ),
    ]
