# Generated by Django 6.0.3 on 2026-04-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.idioma'),
        ),
    ]
