# Generated by Django 6.0.3 on 2026-04-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_idioma_alter_libro_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='anio_publicacion',
        ),
    ]
