# Generated by Django 6.0.3 on 2026-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_libro_anio_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
