# Generated by Django 6.0.3 on 2026-05-26 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_editorial_remove_libro_autor_libro_autores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='año_publicacion',
            field=models.PositiveIntegerField(default=2026, validators=[django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='numero_paginas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
