# Generated by Django 6.0.3 on 2026-06-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('users', '0005_remove_tarjeta_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='tarjeta_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tarjeta'),
        ),
    ]
