# Generated by Django 6.0.3 on 2026-06-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(choices=[('DEFECTUOSO', 'Libro defectuoso o dañado'), ('EQUIVOCADO', 'Recibí un libro incorrecto'), ('INCOMPLETO', 'Libro incompleto'), ('ARREPENTIMIENTO', 'Ya no deseo el producto'), ('OTRO', 'Otro motivo')], max_length=30),
        ),
    ]
