# Generated by Django 6.0.3 on 2026-06-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('devoluciones', '0002_devolucion_descripcion_alter_devolucion_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='devoluciones.devolucion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.itemcarrito')),
            ],
        ),
    ]
