# Generated by Django 6.0.3 on 2026-06-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0003_devolucionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(choices=[('DEFECTUOSO', 'Libro defectuoso o dañado'), ('TiempoSuperior', 'Tiempo de entrega superior al esperado'), ('ARREPENTIMIENTO', 'Ya no deseo el producto')], max_length=30),
        ),
    ]
