# Generated by Django 6.0.3 on 2026-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0004_alter_devolucion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(choices=[('DEFECTUOSO', 'Libro defectuoso o dañado'), ('TiempoSuperior', 'Tiempo de entrega superior al esperado'), ('ARREPENTIMIENTO', 'El libro no lleno mis expectativas')], max_length=30),
        ),
    ]
